### ISSUE TITLE
Having exception

### ISSUE THREAD

**Issue by ursus69** [MorrisJobke/netatmo-influxdb#1]
Hello Morris,
I am trying to use your netatmo import script, but I am having some dificulties,
I am using python 3.4 on ubuntu 14.04, I dont see any requirement of python version other than 3.
My requests is 2.13.0, and influxdb is 4.0.0

at every run there is an exception

Original exception was:
```
Traceback (most recent call last):
  File "get.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python3.4/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 3, in <module>
    import logging
  File "/usr/lib/python3.4/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib/python3.4/traceback.py", line 3, in <module>
    import linecache
  File "/usr/lib/python3.4/linecache.py", line 10, in <module>
    import tokenize
  File "/usr/lib/python3.4/tokenize.py", line 33, in <module>
    from token import *
  File "/home/jose/weather-falcon/token.py", line 12, in <module>
    resp = requests.post('https://api.netatmo.com/oauth2/token', data=data)
AttributeError 

```
Cordially
Jose

**Comment by ursus69** [comment]
You can disregard this comment sorry
