### ISSUE TITLE
Filter wind does not exists

### ISSUE THREAD

**Issue by AndreTzerra** [MorrisJobke/netatmo-influxdb#2]
Hello,

Since I added a additional indoor unit and updated the Netatmo firmware, the script is not working in the right way. After getting the 'rain' data I get the next error:

`Name: Windmeter ID: XX:XX:XX:XX:XX:XX Last seen: 2018-06-24T06:59:54
	Data types: ['Wind'] 
Traceback (most recent call last):
  File "netatmo.py", line 182, in <module>
    iterateStations(token_info['access_token'])
  File "netatmo.py", line 125, in iterateStations
    fetchMeasurements(access_token, station['_id'], substation['_id'], measurement_type, station['station_name'], name, client, substation['last_seen'])
  File "netatmo.py", line 144, in fetchMeasurements
    raise Exception(measurements)
Exception: {'error': {'message': 'Filter wind does not exists', 'code': 21}}
`

Before this last update everything was working?
Is there something changed in the firmware so that the script will not work?

André

**Comment by ghoeffner** [comment]
Seems like this is a breaking API change? The issue still persists.

Fixed this by adding "Wind" to the allowed types and adding the following code on line 65:
`    if measurement_type.lower() in ['wind']:
        measurement_type = "WindStrength,WindAngle,Guststrength,GustAngle"
`

**Comment by AndreTzerra** [comment]
Ghoeffner,

If I try to put it in line 65, I only get errors.
Can you specify where to put the code you added?
Bewteen witch lines?

**Comment by taarhaug** [comment]
Here is the fix implemented after adding 'Wind' to the _ALLOWED_TYPES:

def iterateStations(access_token):
    client = getInfluxDBClient()
    station_info = getStationInfo(access_token)
    if 'body' not in station_info:
        raise Exception(station_info)
    stations = station_info['body']['devices']


    for station in stations:
        printStation(station)
        for measurement_type in station['data_type']:
            fetchMeasurements(access_token, station['_id'], "", measurement_type, station['station_name'], station['module_name'], client, station['last_status_store'])

        print('Modules:')
        for substation in station['modules']:
            printStation(substation)
            if substation['data_type'] == ['Wind']: 
                substation['data_type'] = ['WindStrength','WindAngle','GustStrength', 'GustAngle']

            for measurement_type in substation['data_type']:
                if 'module_name' in substation:
                    name = substation['module_name']
                else:
                    name = substation['_id']
                fetchMeasurements(access_token, station['_id'], substation['_id'], measurement_type, station['station_name'], name, client, substation['last_seen'])



Works great, thank you.

**Comment by taarhaug** [comment]
Err, actually only Wind is written to influx now; not all the data:

> select * from Wind
name: Wind
time                module     station    value
----                ------     -------    -----
1559850870000000000 Wind Gauge AarhaugOne 6
1559851170000000000 Wind Gauge AarhaugOne 6
1559851472000000000 Wind Gauge AarhaugOne 6
